"use client";
import { useEffect,useMemo,useState } from "react";
import { AppPage } from "@/components/app/app-page";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
type Row={date:string;views:number;likes:number;comments:number;shares:number;saves:number;reach:number;engagementRate:number;platform:string};
export default function Analytics(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const me=await fetch("/api/auth/me").then(r=>r.json());const ws=me.data?.workspaces?.[0];if(!ws)return;const r=await fetch(`/api/workspaces/${ws.id}/analytics?days=30`),j=await r.json();if(!r.ok){setError(j.details?.code==="PLAN_REQUIRED"?"Advanced analytics is available on Pro and above.":j.error||"Couldn't load analytics.");return}setRows(j.data||[])}catch{setError("Couldn't load analytics.")}finally{setLoading(false)}})()},[]);
 const totals=useMemo(()=>rows.reduce((a,r)=>({views:a.views+r.views,likes:a.likes+r.likes,comments:a.comments+r.comments,shares:a.shares+r.shares,saves:a.saves+r.saves,reach:a.reach+r.reach}),{views:0,likes:0,comments:0,shares:0,saves:0,reach:0}),[rows]);
 const byDay=useMemo(()=>Object.entries(rows.reduce<Record<string,number>>((a,r)=>(a[r.date.slice(0,10)]=(a[r.date.slice(0,10)]||0)+r.views,a),{})).slice(-14),[rows]);
 if(loading)return <AppPage><div className="h-[600px] animate-pulse rounded-3xl bg-zinc-100"/></AppPage>;
 return <AppPage><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="rounded-full bg-orange-100 px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-orange-700">Performance</span><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">See what's actually working.</h1><p className="mt-2 text-sm text-zinc-500">Real performance data from the last 30 days.</p></div><Button href="/app/connections" variant="secondary">Manage connections</Button></div>{error?<div className="mt-6 rounded-2xl border border-orange-200 bg-orange-50 p-5 text-sm text-orange-800">{error}</div>:<><div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Views",totals.views],["Reach",totals.reach],["Likes",totals.likes],["Saves",totals.saves]].map(([k,v])=><Card key={k} className="p-5"><p className="text-xs text-zinc-400">{k}</p><p className="mt-2 text-2xl font-semibold">{Number(v).toLocaleString()}</p><p className="mt-1 text-xs text-zinc-400">{rows.length} analytics snapshots</p></Card>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_.75fr]"><Card className="p-5 sm:p-6"><p className="text-xs uppercase tracking-wide text-zinc-400">Views</p><h2 className="mt-1 text-xl font-semibold">Last 14 days</h2>{byDay.length?<div className="mt-8 flex h-64 items-end gap-2">{byDay.map(([day,value])=>{const max=Math.max(...byDay.map(x=>x[1]));return <div key={day} className="flex h-full flex-1 flex-col justify-end gap-2"><div title={`${day}: ${value.toLocaleString()} views`} className="w-full rounded-t-lg bg-orange-500" style={{height:`${Math.max(5,(value/max)*100)}%`}}/><span className="truncate text-center text-[9px] text-zinc-400">{day.slice(5)}</span></div>})}</div>:<div className="grid h-64 place-items-center text-sm text-zinc-400">No analytics data yet.</div>}</Card><Card className="bg-zinc-950 p-6 text-white"><p className="text-xs uppercase tracking-wide text-orange-300">Engagement</p><p className="mt-2 text-4xl font-semibold">{totals.views?((totals.likes+totals.comments+totals.shares+totals.saves)/totals.views*100).toFixed(2):"0.00"}%</p><p className="mt-3 text-sm leading-6 text-zinc-400">Calculated from your real likes, comments, shares, saves, and views.</p><div className="mt-7 space-y-3">{[["Likes",totals.likes],["Comments",totals.comments],["Shares",totals.shares],["Saves",totals.saves]].map(x=><div key={x[0]} className="flex justify-between rounded-xl bg-white/5 p-3 text-xs"><span className="text-zinc-400">{x[0]}</span><span>{Number(x[1]).toLocaleString()}</span></div>)}</div></Card></div></>}</AppPage>
}