"use client";

import Link from "next/link";
import { useState } from "react";

const actions = [
  ["Turn your strongest topic into a 3-part series.", "High", "Content DNA found repeated engagement around creator growth.", "Create series"],
  ["Remix your highest-retention talking-head format.", "High", "Your direct hooks are outperforming your other hook shapes.", "Open Create"],
  ["Refresh your Instagram connection.", "Medium", "The connection needs attention before new analytics can sync.", "Connections"],
  ["Add your main offer to Brand Brain.", "Medium", "Knowing the offer lets Contentra connect content to conversion.", "Update Brand Brain"]
];

export default function NextActionsPage() {
  const [done, setDone] = useState<number[]>([]);
  return <main className="min-h-screen bg-[#f7f7f5] text-zinc-950"><div className="mx-auto flex min-h-screen max-w-[1500px]"><Sidebar active="Next Best Action"/><section className="min-w-0 flex-1"><header className="sticky top-0 z-30 border-b border-zinc-200/80 bg-[#f7f7f5]/90 px-4 py-3 backdrop-blur-xl sm:px-6"><div className="mx-auto flex max-w-6xl items-center justify-between"><div><p className="text-sm font-semibold">Next Best Action</p><p className="text-xs text-zinc-500">A prioritized list of what to do next.</p></div><button className="rounded-full border border-zinc-200 bg-white px-4 py-2 text-xs font-semibold">Refresh signals</button></div></header><div className="mx-auto max-w-6xl px-4 py-7 sm:px-6"><div className="rounded-[28px] border border-orange-200 bg-orange-50 p-6 sm:p-8"><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-orange-700">CONTENTRA INTELLIGENCE</span><h1 className="mt-4 max-w-3xl text-3xl font-semibold tracking-tight sm:text-4xl">Don't just know what is happening. Know what to do about it.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-orange-950/60">Recommendations combine Brand Brain, Content DNA, content performance, and workspace signals into concrete actions.</p></div><div className="mt-6 space-y-3">{actions.map(([title,priority,reason,cta],i)=>{const complete=done.includes(i);return <div key={title} className={`rounded-[24px] border bg-white p-5 shadow-sm transition ${complete?"border-emerald-200 opacity-60":"border-zinc-200"}`}><div className="flex flex-col gap-5 md:flex-row md:items-center"><div className="grid size-11 shrink-0 place-items-center rounded-2xl bg-zinc-950 text-xs font-bold text-white">{String(i+1).padStart(2,"0")}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold">{title}</h2><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${priority==="High"?"bg-orange-50 text-orange-700":"bg-zinc-100 text-zinc-500"}`}>{priority} priority</span></div><p className="mt-2 text-xs leading-5 text-zinc-500">{reason}</p></div><div className="flex gap-2"><button onClick={()=>setDone(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i])} className="rounded-full border border-zinc-200 px-4 py-2 text-xs font-semibold">{complete?"Completed":"Done"}</button><Link href={cta==="Connections"?"/app/connections":cta==="Update Brand Brain"?"/app/brand-brain":"/app/create"} className="rounded-full bg-zinc-950 px-4 py-2 text-xs font-semibold text-white hover:bg-orange-500">{cta}</Link></div></div></div>})}</div></div></section></div></main>;
}
function Sidebar({active}:{active:string}){const items=[["Overview","/app"],["Create","/app/create"],["Creatos","/app/creatos"],["Library","/app/library"],["Analytics","/app/analytics"],["Next Best Action","/app/next-actions"],["Content DNA","/app/content-dna"],["Brand Brain","/app/brand-brain"],["Campaigns","/app/campaigns"]];return <aside className="hidden w-64 shrink-0 border-r border-zinc-200 bg-white p-4 lg:flex lg:flex-col"><Link href="/" className="flex items-center gap-2 px-2 py-3 font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-xl bg-orange-500 text-sm font-black text-white">C</span>Contentra</Link><nav className="mt-7 space-y-1">{items.map(([label,href])=><Link key={label} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${active===label?"bg-orange-50 text-orange-700":"text-zinc-500 hover:bg-zinc-50 hover:text-zinc-950"}`}><span className="grid size-7 place-items-center rounded-lg bg-zinc-100 text-[10px]">{label.slice(0,1)}</span>{label}</Link>)}</nav></aside>}
