"use client";

import Link from "next/link";
import { useState } from "react";

const initial = [
  ["Yeezy", "Owner", "Active", "Owner"],
  ["Alex Morgan", "Admin", "Active", "Admin"],
  ["Jordan Lee", "Member", "Active", "Member"],
  ["Sam Rivera", "Viewer", "Invited", "Viewer"]
];

export default function TeamPage() {
  const [members,setMembers]=useState(initial);
  const [invited,setInvited]=useState(false);
  return <main className="min-h-screen bg-[#f7f7f5] text-zinc-950"><div className="mx-auto flex min-h-screen max-w-[1500px]"><Sidebar active="Team"/><section className="min-w-0 flex-1"><header className="sticky top-0 z-30 border-b border-zinc-200/80 bg-[#f7f7f5]/90 px-4 py-3 backdrop-blur-xl sm:px-6"><div className="mx-auto flex max-w-6xl items-center justify-between"><div><p className="text-sm font-semibold">Team</p><p className="text-xs text-zinc-500">Manage workspace access and roles.</p></div><button onClick={()=>setInvited(true)} className="rounded-full bg-orange-500 px-4 py-2 text-xs font-semibold text-white hover:bg-orange-600">{invited?"Invite sent":"Invite member"}</button></div></header><div className="mx-auto max-w-6xl px-4 py-7 sm:px-6"><div className="grid gap-4 md:grid-cols-3"><Stat title="Members" value={String(members.length)} detail="Workspace seats"/><Stat title="Admins" value="2" detail="Can manage workspace"/><Stat title="Pending" value="1" detail="Invitation awaiting access"/></div><div className="mt-6 overflow-hidden rounded-[26px] border border-zinc-200 bg-white shadow-sm"><div className="border-b border-zinc-100 px-5 py-4"><p className="text-sm font-semibold">Workspace members</p></div><div className="divide-y divide-zinc-100">{members.map((m,i)=><div key={m[0]} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center"><div className="grid size-9 shrink-0 place-items-center rounded-full bg-orange-100 text-xs font-semibold text-orange-700">{m[0].slice(0,1)}</div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{m[0]}</p><p className="text-xs text-zinc-500">{m[1]} · {m[2]}</p></div><select value={m[3]} onChange={e=>setMembers(v=>v.map((x,j)=>j===i?[x[0],x[1],x[2],e.target.value]:x))} className="rounded-xl border border-zinc-200 bg-white px-3 py-2 text-xs font-medium"><option>Owner</option><option>Admin</option><option>Member</option><option>Viewer</option></select></div>)}</div></div><div className="mt-6 rounded-[24px] border border-zinc-200 bg-white p-5"><p className="text-sm font-semibold">Roles & permissions</p><p className="mt-1 text-xs leading-5 text-zinc-500">Owners and admins can manage workspace settings, connections, billing, and members. Members can create and manage content. Viewers have read-only access.</p></div></div></section></div></main>;
}
function Stat({title,value,detail}:{title:string,value:string,detail:string}){return <div className="rounded-[22px] border border-zinc-200 bg-white p-5 shadow-sm"><p className="text-xs text-zinc-500">{title}</p><p className="mt-2 text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-zinc-400">{detail}</p></div>}
function Sidebar({active}:{active:string}){const items=[["Overview","/app"],["Create","/app/create"],["Creatos","/app/creatos"],["Library","/app/library"],["Analytics","/app/analytics"],["Campaigns","/app/campaigns"],["Team","/app/team"],["Connections","/app/connections"],["Settings","/app/settings"]];return <aside className="hidden w-64 shrink-0 border-r border-zinc-200 bg-white p-4 lg:flex lg:flex-col"><Link href="/" className="flex items-center gap-2 px-2 py-3 font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-xl bg-orange-500 text-sm font-black text-white">C</span>Contentra</Link><nav className="mt-7 space-y-1">{items.map(([label,href])=><Link key={label} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${active===label?"bg-orange-50 text-orange-700":"text-zinc-500 hover:bg-zinc-50 hover:text-zinc-950"}`}><span className="grid size-7 place-items-center rounded-lg bg-zinc-100 text-[10px]">{label.slice(0,1)}</span>{label}</Link>)}</nav></aside>}
