"use client";
import { useEffect,useState } from "react";
import { AppPage } from "@/components/app/app-page";
import { Card,CardHeader } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
type Brain={businessName:string|null;niche:string|null;audience:string|null;positioning:string|null;voice:string|null;websiteUrl:string|null;goals:string[];offers:string[];competitors:string[];contentPillars:string[];completeness:number};
export default function BrandBrain(){const [brain,setBrain]=useState<Brain|null>(null),[saving,setSaving]=useState(false),[scanning,setScanning]=useState(false),[url,setUrl]=useState(""),[message,setMessage]=useState("");
useEffect(()=>{(async()=>{const me=await fetch("/api/auth/me").then(r=>r.json()),ws=me.data?.workspaces?.[0];if(!ws)return;const r=await fetch(`/api/workspaces/${ws.id}/brand-brain`),j=await r.json();if(r.ok){setBrain(j.data);setUrl(j.data.websiteUrl||"")}})()},[]);
function field(key:keyof Brain){return <textarea value={String(brain?.[key]??"")} onChange={e=>setBrain(b=>b?{...b,[key]:e.target.value}:b)} className="mt-2 min-h-24 w-full resize-y rounded-2xl border border-zinc-200 bg-zinc-50 p-3 text-sm outline-none focus:border-orange-400"/>}
async function save(){if(!brain)return;setSaving(true);const me=await fetch("/api/auth/me").then(r=>r.json()),ws=me.data?.workspaces?.[0];const r=await fetch(`/api/workspaces/${ws.id}/brand-brain`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...brain,websiteUrl:url})});const j=await r.json();if(r.ok){setBrain(j.data);setMessage("Saved")}else setMessage(j.error||"Couldn't save");setSaving(false)}
async function scan(){if(!brain||!url)return;setScanning(true);setMessage("");const me=await fetch("/api/auth/me").then(r=>r.json()),ws=me.data?.workspaces?.[0];const r=await fetch(`/api/workspaces/${ws.id}/brand-brain/ingest`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({websiteUrl:url})});const j=await r.json();if(r.ok)setBrain(j.data);else setMessage(j.error||"Website scan failed");setScanning(false)}
if(!brain)return <AppPage><div className="h-[600px] animate-pulse rounded-3xl bg-zinc-100"/></AppPage>;
return <AppPage><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="rounded-full bg-orange-100 px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-orange-700">Brand Brain</span><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Teach Contentra your brand.</h1><p className="mt-2 max-w-2xl text-sm text-zinc-500">This context powers generation, recommendations, opportunities, and Content DNA.</p></div><Button onClick={save}>{saving?"Saving...":message==="Saved"?"Saved":"Save changes"}</Button></div><Card className="mt-7 bg-zinc-950 text-white"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-wide text-orange-300">Completeness</p><p className="mt-1 text-4xl font-semibold">{brain.completeness}%</p></div><div className="w-full max-w-md"><div className="h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-orange-500" style={{width:`${brain.completeness}%`}}/></div><p className="mt-2 text-xs text-zinc-500">More context gives Contentra stronger outputs.</p></div></div></Card><div className="mt-6 grid gap-5 md:grid-cols-2"><Card><CardHeader title="Business" description="What you sell and what makes you different."/><div className="px-5 pb-5 sm:px-6">{field("businessName")}{field("niche")}</div></Card><Card><CardHeader title="Audience" description="Who Contentra should speak to."/><div className="px-5 pb-5 sm:px-6">{field("audience")}</div></Card><Card><CardHeader title="Positioning" description="The promise and angle your brand should own."/><div className="px-5 pb-5 sm:px-6">{field("positioning")}</div></Card><Card><CardHeader title="Voice" description="How your content should sound."/><div className="px-5 pb-5 sm:px-6">{field("voice")}</div></Card></div><Card className="mt-5"><CardHeader title="Website intelligence" description="Scan your public website and let Contentra extract useful brand context."/><div className="flex flex-col gap-3 px-5 pb-5 sm:flex-row sm:px-6 sm:pb-6"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://yourwebsite.com" className="min-w-0 flex-1 rounded-xl border border-zinc-200 bg-zinc-50 px-4 py-3 text-sm outline-none focus:border-orange-400"/><Button onClick={scan} variant="secondary">{scanning?"Scanning...":"Scan website"}</Button></div>{message&&<p className="px-5 pb-5 text-xs text-zinc-500 sm:px-6">{message}</p>}</Card></AppPage>}
